# Generated by Django 4.1.5 on 2023-01-25 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(blank=True, max_length=30, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=30, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=5, verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(blank=True, max_length=255, verbose_name='Название продукта')),
                ('product_model', models.CharField(blank=True, max_length=100, verbose_name='Модель продукта')),
                ('date_out', models.DateField(verbose_name='Дата выхода продукта на рынок')),
                ('quantity', models.IntegerField(blank=True, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Subject_net',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название субъекта')),
                ('created_date', models.DateField(verbose_name='Дата создания')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_link.contact', verbose_name='Контакты')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_link.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Субъект сети',
                'verbose_name_plural': 'Субъекты сети',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrears', models.FloatField(blank=True, verbose_name='Задолженность')),
                ('providers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_link.subject_net', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
    ]
