# Generated by Django 4.1.5 on 2023-01-25 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail_link', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='subjects',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='retail_link.subject_net', verbose_name='Субъект сети'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider',
            name='providers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='retail_link.subject_net', verbose_name='Поставщик'),
        ),
    ]
